### PR TITLE
range indication

### PR DESCRIPTION
**Pull request by OceanUwU**
a red box to show what's in range when a player uses .board

here's what it currently looks like:
image

i admit its not the prettiest and may need a bit of tweaking

### CODE REVIEW

**Comment by TheFloyds4240** [comment]
looks cool to me.

**Comment by TheFloyds4240** [comment]
What if you made it a circle instead of a square?

**Comment by OceanUwU** [comment]
hold on i think the range is measured differently than just "u have a square of radius x" i may have to redo this

**Comment by OceanUwU** [comment]
https://github.com/Imanton1/Discordpy-TankGame/blob/42b7b580cbe5730bba356f8996b6a540671d9c42/tank.py#L49
isn't this chebyshev distance, and not manhattan distance?

**Comment by Imanton1** [comment]
Also have fixed the chebyshev/manhattan problem.

**Comment by OceanUwU** [comment]
its technically currently public because you can discord search "from:user .upgrade" and count those. in the original tank tactics im pretty sure everything was publicly logged except AP gifting. otherwise, there could just be a `-r` option for .board

**Comment by OceanUwU** [comment]
updated to require `-r`

**Pull request merged**
